-- MySQL Script generated by MySQL Workbench
-- Wed Jul 11 15:50:02 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema javaschool
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema javaschool
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `javaschool` DEFAULT CHARACTER SET utf8 ;
USE `javaschool` ;

-- -----------------------------------------------------
-- Table `javaschool`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `javaschool`.`user` ;

CREATE TABLE IF NOT EXISTS `javaschool`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `accessLevel` ENUM('customer', 'admin') NULL DEFAULT 'customer',
  `firstname` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  `birthday` DATE NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `javaschool`.`station`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `javaschool`.`station` ;

CREATE TABLE IF NOT EXISTS `javaschool`.`station` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `longitude` DECIMAL(65) NULL,
  `latitude` DECIMAL(65) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

INSERT INTO station (name) VALUES ('Moscow');
INSERT INTO station (name) VALUES ('Voronezh');
INSERT INTO station (name) VALUES ('Saratov');
INSERT INTO station (name) VALUES ('Samara');
INSERT INTO station (name) VALUES ('Kazan');
INSERT INTO station (name) VALUES ('Nizhniy-Novgorod');


-- -----------------------------------------------------
-- Table `javaschool`.`train`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `javaschool`.`train` ;

CREATE TABLE IF NOT EXISTS `javaschool`.`train` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `seats_amount` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

INSERT INTO train (name, seats_amount) VALUES ("train1", 56);
INSERT INTO train (name, seats_amount) VALUES ("train2", 50);


-- -----------------------------------------------------
-- Table `javaschool`.`routeSchedule`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `javaschool`.`routeSchedule` ;

CREATE TABLE IF NOT EXISTS `javaschool`.`routeSchedule` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `train_id` INT NOT NULL,
  `station_id` INT NOT NULL,
  `station_order` INT NOT NULL,
  `time_arrival` VARCHAR(45),
  `time_departure` VARCHAR(45),
  PRIMARY KEY (`id`, `train_id`, `station_id`),
  INDEX `fk_schedule_station1_idx` (`station_id` ASC),
  INDEX `fk_schedule_train1_idx` (`train_id` ASC),
  CONSTRAINT `fk_schedule_station1`
    FOREIGN KEY (`station_id`)
    REFERENCES `javaschool`.`station` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_schedule_train1`
    FOREIGN KEY (`train_id`)
    REFERENCES `javaschool`.`train` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

-- FIRST TRAIN ROUTE 
INSERT INTO routeSchedule (train_id, station_id, station_order, time_arrival, time_departure) VALUES (1, 1, 0, "arr", "dep");
INSERT INTO routeSchedule (train_id, station_id, station_order, time_arrival, time_departure) VALUES (1, 6, 1, "arr", "dep");
INSERT INTO routeSchedule (train_id, station_id, station_order, time_arrival, time_departure) VALUES (1, 5, 2, "arr", "dep");
INSERT INTO routeSchedule (train_id, station_id, station_order, time_arrival, time_departure) VALUES (1, 4, 3, "arr", "dep");
INSERT INTO routeSchedule (train_id, station_id, station_order, time_arrival, time_departure) VALUES (1, 3, 4, "arr", "dep");
-- SECOND TRAIN ROUTE
INSERT INTO routeSchedule (train_id, station_id, station_order, time_arrival, time_departure) VALUES (2, 1, 0, "arr", "dep");
INSERT INTO routeSchedule (train_id, station_id, station_order, time_arrival, time_departure) VALUES (2, 2, 1, "arr", "dep");
INSERT INTO routeSchedule (train_id, station_id, station_order, time_arrival, time_departure) VALUES (2, 3, 2, "arr", "dep");



-- -----------------------------------------------------
-- Table `javaschool`.`trip`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `javaschool`.`trip` ;

CREATE TABLE IF NOT EXISTS `javaschool`.`trip` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `routeSchedule_train_id` INT NOT NULL,
  PRIMARY KEY (`id`, `routeSchedule_train_id`),
  INDEX `fk_trip_routeSchedule1_idx` (`routeSchedule_train_id` ASC),
  CONSTRAINT `fk_trip_routeSchedule1`
    FOREIGN KEY (`routeSchedule_train_id`)
    REFERENCES `javaschool`.`routeSchedule` (`train_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `javaschool`.`seats`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `javaschool`.`seats` ;

CREATE TABLE IF NOT EXISTS `javaschool`.`seats` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `seat_id` INT NOT NULL,
  `availability` TINYINT NOT NULL,
  `trip_id` INT NOT NULL,
  PRIMARY KEY (`id`, `trip_id`),
  INDEX `fk_seats_trip1_idx` (`trip_id` ASC),
  CONSTRAINT `fk_seats_trip1`
    FOREIGN KEY (`trip_id`)
    REFERENCES `javaschool`.`trip` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `javaschool`.`ticket`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `javaschool`.`ticket` ;

CREATE TABLE IF NOT EXISTS `javaschool`.`ticket` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `trip_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `seats_id` INT NOT NULL,
  PRIMARY KEY (`id`, `trip_id`, `user_id`, `seats_id`),
  INDEX `fk_ticket_trip1_idx` (`trip_id` ASC),
  INDEX `fk_ticket_user1_idx` (`user_id` ASC),
  INDEX `fk_ticket_seats1_idx` (`seats_id` ASC, `trip_id` ASC),
  CONSTRAINT `fk_ticket_trip1`
    FOREIGN KEY (`trip_id`)
    REFERENCES `javaschool`.`trip` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ticket_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `javaschool`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ticket_seats1`
    FOREIGN KEY (`seats_id` , `trip_id`)
    REFERENCES `javaschool`.`seats` (`id` , `trip_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
