-- MySQL Script generated by MySQL Workbench
-- Tue Jul 31 13:16:56 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema javaschool
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema javaschool
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `javaschool` DEFAULT CHARACTER SET utf8 ;
USE `javaschool` ;

-- -----------------------------------------------------
-- Table `javaschool`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `javaschool`.`user` ;

CREATE TABLE IF NOT EXISTS `javaschool`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `role` VARCHAR(45) NOT NULL DEFAULT 1,
  `firstname` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  `birthday` DATE NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `javaschool`.`train`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `javaschool`.`train` ;

CREATE TABLE IF NOT EXISTS `javaschool`.`train` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `speed` DECIMAL NOT NULL,
  `seats_amount` INT NOT NULL,
  `carriage_amount` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `javaschool`.`trip`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `javaschool`.`trip` ;

CREATE TABLE IF NOT EXISTS `javaschool`.`trip` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `train_id` INT NOT NULL,
  `route_id` INT NOT NULL,
  `start_time` TIMESTAMP NOT NULL,
  `time_late` VARCHAR(5) NOT NULL DEFAULT '00:00',
  `active` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`, `train_id`),
  INDEX `fk_trip_train1_idx` (`train_id` ASC),
  CONSTRAINT `fk_trip_train1`
    FOREIGN KEY (`train_id`)
    REFERENCES `javaschool`.`train` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `javaschool`.`ticket`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `javaschool`.`ticket` ;

CREATE TABLE IF NOT EXISTS `javaschool`.`ticket` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `trip_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `seat_id` INT NOT NULL,
  `carriage_num` INT NOT NULL,
  PRIMARY KEY (`id`, `trip_id`, `user_id`, `seat_id`, `carriage_num`),
  INDEX `fk_ticket_trip1_idx` (`trip_id` ASC),
  INDEX `fk_ticket_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_ticket_trip1`
    FOREIGN KEY (`trip_id`)
    REFERENCES `javaschool`.`trip` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ticket_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `javaschool`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `javaschool`.`station`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `javaschool`.`station` ;

CREATE TABLE IF NOT EXISTS `javaschool`.`station` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `longitude` DECIMAL(65,5) NOT NULL,
  `latitude` DECIMAL(65,5) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `javaschool`.`route`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `javaschool`.`route` ;

CREATE TABLE IF NOT EXISTS `javaschool`.`route` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `route_id` INT NOT NULL,
  `station_id` INT NOT NULL,
  `station_order` INT NULL,
  PRIMARY KEY (`id`, `station_id`),
  INDEX `fk_route_station1_idx` (`station_id` ASC),
  CONSTRAINT `fk_route_station1`
    FOREIGN KEY (`station_id`)
    REFERENCES `javaschool`.`station` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `javaschool`.`schedule`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `javaschool`.`schedule` ;

CREATE TABLE IF NOT EXISTS `javaschool`.`schedule` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `trip_id` INT NOT NULL,
  `station_id` INT NOT NULL,
  `time_arrival` TIMESTAMP NULL,
  `time_stop` VARCHAR(45) NULL,
  `time_departure` TIMESTAMP NULL,
  PRIMARY KEY (`id`, `trip_id`, `station_id`),
  INDEX `fk_schedule_trip1_idx` (`trip_id` ASC),
  INDEX `fk_schedule_station1_idx` (`station_id` ASC),
  CONSTRAINT `fk_schedule_trip1`
    FOREIGN KEY (`trip_id`)
    REFERENCES `javaschool`.`trip` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_schedule_station1`
    FOREIGN KEY (`station_id`)
    REFERENCES `javaschool`.`station` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
